import NavBar from "@/components/NavBar";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import SearchBar from "@/components/Searchbar";
import SeachCartCom from "@/components/SeachCartCom";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-robotoFont">
        <Header />
        <NavBar />
        <SeachCartCom />
        {children}
        <Footer />
      </body>
    </html>
  );
}
